name: 'Bump Version'
on:
  pull_request_target:
    types:
      - synchronize
      - edited
      - ready_for_review
      - labeled

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'release/')"
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Pull Request Semver Action
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

